### ISSUE TITLE
Package 1.6

### ISSUE THREAD

**Issue by vast** [fs/fs-tool#57]
List of issues which need some love;
- [x] #54 (add latest guide sections)
- [x] #53 (fix `fs new static`)
- [x] #47 (`fs config init`)

As always, we should also
- [x] update gh-pages branch (website)
- [x] release brew version

/cc @juggler
